version: "3.7"

x-common-variables: &common-variables
    MYSQL_USER: root
    MYSQL_PASSWORD: admin@123
    MYSQL_DATABASE: fampay_test

services: 
    ts-node-docker:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        volumes: 
            - ./src:/home/node/app/src
            - ./nodemon.json:/home/node/app/nodemon.json
        depends_on:
            - mysql-db
        environment:
            <<: *common-variables
            MYSQL_HOST_IP: localhost
        container_name: ts-node-docker
        expose:
            - '5000'
        ports:
            - '5000:5000'
        links:
            - mysql-db
        command: npm run dev
    mysql-db:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: mysql_container
        environment:
            <<: *common-variables
            MYSQL_HOST: localhost
            MYSQL_ROOT_PASSWORD: admin@123
        ports:
            - 3308:3306
        restart: always
        expose: 
            - 3306
        volumes:
            - ./db/sample.sql:/docker-entrypoint-initdb.d/sample.sql